<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,3,1,'087Pt73pydw=');
$cfg_Cs[2]=array(0,1,1,'1K3BptDCzsU=');
$cfg_Cs[3]=array(0,1,1,'udjT2s7Sw8c=');
$cfg_Cs[4]=array(0,1,1,'warPtc7Sw8c=');
$cfg_Cs[5]=array(0,1,1,'vNPI687Sw8c=');
$cfg_Cs[6]=array(5,1,1,'vLzK9cDg');
$cfg_Cs[7]=array(5,1,1,'1MvTqsDg');
$cfg_Cs[8]=array(5,1,1,'yei8xsDg');
$cfg_Cs[9]=array(5,1,1,'1rDE3MDg');
$cfg_Cs[10]=array(0,1,1,'08O7p9bQ0MQ=');
$cfg_Cs[11]=array(0,1,1,'16Ky4Q==');
$cfg_Cs[12]=array(0,1,1,'yrXD+8jP1qQ=');
$cfg_Cs[13]=array(0,1,1,'tcfCvA==');
?>