<li  title="[field:title/]">
						<h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
						<div class="gamepic"><a href="[field:arcurl/]" title="[field:title/]"><img src='[field:litpic/]' height="195" width="331" alt="[field:title/]"></a></div>
						<div class="gamelink">
							<span class="android">
								<a href="http://download.6513.com/phoneGame/8888903BY.apk">下载游戏</a>
							</span>
							<span class="ewmlink"><a href="#">二维码下载</a><i><img src="/templets/default/pic/116.png" alt=""></i></span>
						</div>
					</li>