<li title="[field:title/]">
						<h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
						<div class="gamepic"><a href="[field:arcurl/]" title="[field:title/]"><img src='[field:litpic/]' height="195" width="331" alt="[field:title/]"></a></div>
						<div class="gamelink">
							<span class="appstore">
								<a href="https://itunes.apple.com/cn/app/jie-ji-qian-pao-bu-yu/id948569950?mt=8" target="_blank">App Store</a>
							</span>
							<span class="ewmlink">
								<a href="javascript:void(0);">╤Чн╛бКобть</a>
								<i><img src="/templets/default/pic/116.png" alt=""></i>
							</span>
						</div>
					</li>