<?php
$z[0]=Array("global","",77,109);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",181,213);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",311,343);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",573,598);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channelartlist","\r\n				<a href='{dede:field name='typeurl'/}' id='{dede:field name='typeid'/}'>\r\n					{dede:field name='typename'/}\r\n				</a>\r\n			",630,837);
$z[4][4]['typeid']="1,2,3,4,10,11,12";
$z[4][4]['row']="7";

?>