<?php
$z[0]=Array("field","",65,84);
$z[0][4]['name']="title";
$z[1]=Array("global","",85,111);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",152,179);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",219,249);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",255,290);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",506,535);
$z[5][4]['name']="position";
$z[6]=Array("type"," \r\n			<h2 class=\"game_t\">[field:typename/]</h2>\r\n		",554,639);
$z[6][4]['typeid']="1";
$z[7]=Array("list","\r\n					<li title=\"[field:title/]\">\r\n						<h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n						<div class=\"gamepic\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src='[field:litpic/]' height=\"195\" width=\"331\" alt=\"[field:title/]\"></a></div>\r\n						<div class=\"gamelink\">\r\n							<span class=\"appstore\">\r\n								<a href=\"https://itunes.apple.com/cn/app/jie-ji-qian-pao-bu-yu/id948569950?mt=8\" target=\"_blank\">App Store</a>\r\n							</span>\r\n							<span class=\"ewmlink\">\r\n								<a href=\"javascript:void(0);\">二维码下载</a>\r\n								<i><img src=\"/templets/default/pic/116.png\" alt=\"\"></i>\r\n							</span>\r\n						</div>\r\n					</li>\r\n					",1096,1824);
$z[7][4]['pagesize']="9";
$z[7][4]['orderby']="click";
$z[8]=Array("pagelist","",1871,1942);
$z[8][4]['istitem']="index,pre,next,end,option,info,";
$z[8][4]['listsize']="5";
$z[9]=Array("list","\r\n					<li  title=\"[field:title/]\">\r\n						<h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n						<div class=\"gamepic\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src='[field:litpic/]' height=\"195\" width=\"331\" alt=\"[field:title/]\"></a></div>\r\n						<div class=\"gamelink\">\r\n							<span class=\"android\">\r\n								<a href=\"http://download.6513.com/phoneGame/8888903BY.apk\">下载游戏</a>\r\n							</span>\r\n							<span class=\"ewmlink\"><a href=\"#\">二维码下载</a><i><img src=\"/templets/default/pic/116.png\" alt=\"\"></i></span>\r\n						</div>\r\n					</li>\r\n					",2037,2679);
$z[9][4]['pagesize']="9";
$z[9][4]['orderby']="click";
$z[10]=Array("pagelist","",2725,2796);
$z[10][4]['istitem']="index,pre,next,end,option,info,";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",3398,3433);
$z[11][4]['filename']="foot.htm";

?>