<?php
$z[0]=Array("field","",65,84);
$z[0][4]['name']="title";
$z[1]=Array("global","",85,111);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",152,179);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",219,249);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",255,290);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",508,537);
$z[5][4]['name']="position";
$z[6]=Array("type","  \r\n				<h2 class=\"news_t\">[field:typename/]</h2>\r\n			",557,646);
$z[6][4]['typeid']="12";
$z[7]=Array("list","\r\n					<li>\r\n						<em>[field:pubdate function=\"GetDateTimeMK(@me)\" /]</em>\r\n						<a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a>\r\n					</li>\r\n					",772,977);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",1033,1104);
$z[8][4]['istitem']="index,pre,next,end,option,info,";
$z[8][4]['listsize']="5";
$z[9]=Array("global","",1355,1387);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("include","",1521,1556);
$z[10][4]['filename']="foot.htm";

?>