<?php
$z[0]=Array("field","",65,84);
$z[0][4]['name']="title";
$z[1]=Array("global","",85,111);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",152,179);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",219,249);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",255,290);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",507,536);
$z[5][4]['name']="position";
$z[6]=Array("arclist","\r\n							<dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title /]</a><em></em></dt>\r\n							<dd>\r\n								[field:description function='cn_substr(@me,300)'/]......<br/>\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\" style=\"float:right;margin-right:10px;\">查看更多</a>\r\n							</dd>\r\n							\r\n							",1085,1486);
$z[6][4]['typeid']="6";
$z[6][4]['orderby']="pubdate";
$z[6][4]['titlelen']="50";
$z[6][4]['row']="9";
$z[7]=Array("arclist","\r\n							<dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title /]</a><em></em></dt>\r\n							<dd>\r\n								[field:description function='cn_substr(@me,300)'/]......<br/>\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\" style=\"float:right;margin-right:10px;\">查看更多</a>\r\n							</dd>\r\n							\r\n							",1595,1996);
$z[7][4]['typeid']="7";
$z[7][4]['orderby']="pubdate";
$z[7][4]['titlelen']="50";
$z[7][4]['row']="9";
$z[8]=Array("arclist","\r\n							<dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title /]</a><em></em></dt>\r\n							<dd>\r\n								[field:description function='cn_substr(@me,300)'/]......<br/>\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\" style=\"float:right;margin-right:10px;\">查看更多</a>\r\n							</dd>\r\n						\r\n							",2087,2487);
$z[8][4]['typeid']="8";
$z[8][4]['orderby']="pubdate";
$z[8][4]['titlelen']="50";
$z[8][4]['row']="9";
$z[9]=Array("arclist","\r\n							<dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title /]</a><em></em></dt>\r\n							<dd>\r\n								[field:description function='cn_substr(@me,300)'/]......<br/>\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\" style=\"float:right;margin-right:10px;\">查看更多</a>\r\n							</dd>\r\n							\r\n							",2578,2979);
$z[9][4]['typeid']="9";
$z[9][4]['orderby']="pubdate";
$z[9][4]['titlelen']="50";
$z[9][4]['row']="9";
$z[10]=Array("include","",3046,3085);
$z[10][4]['filename']="rightbar.htm";
$z[11]=Array("include","",3254,3289);
$z[11][4]['filename']="foot.htm";

?>