<?php
$z[0]=Array("field","",65,84);
$z[0][4]['name']="title";
$z[1]=Array("global","",85,111);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",152,179);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",219,249);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",255,290);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","  \r\n			<h2 class=\"news_t\">[field:typename/]</h2>\r\n		",809,896);
$z[5][4]['typeid']="10";
$z[6]=Array("include","",1194,1229);
$z[6][4]['filename']="foot.htm";

?>